{% set name = "cgsi-gsoap" %}
{% set version = "1.3.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.cern.ch/dmc/{{ name }}/-/archive/v{{ version }}/{{ name }}-v{{ version }}.tar.gz
  sha256: 630f78b2402b30bd9e1ecbfbeda638745d98638e6de0544ae0b493875647a26d

build:
  number: 0
  skip: true  # [win]
  run_exports:
    # Only pin on Linux as static libaries are used on macOS
    - {{ pin_subpackage(name, max_pin='x.x') }}  # [linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cmake
    - make
    - pkg-config
    - gsoap
  host:
    - gsoap
    - voms
    - gct
    - openssl
  run:
    - voms

test:
  commands:
    - test -f "${CONDA_PREFIX}/lib/libcgsi_plugin.a"  # [osx]
    - test -f "${CONDA_PREFIX}/lib/libcgsi_plugin.so"  # [linux]

about:
  home: https://dmc.web.cern.ch/projects-tags/cgsi-gsoap
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Client and server side library to secure gSOAP using the Globus Security Infrastructure'
  doc_url: https://dmc-docs.web.cern.ch/dmc-docs/cgsi-gsoap.html
  dev_url: https://gitlab.cern.ch/dmc/cgsi-gsoap

extra:
  recipe-maintainers:
    - chrisburr
